services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    networks:
      - internal

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/var/www/stream_sh/uploads:ro
      - hls_data:/tmp/hls
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - internal
      - public

volumes:
  uploads_data:
  hls_data:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
